FROM python:3.10

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y mysql\*
RUN pip install mysqlclient
COPY . /app/

EXPOSE 8000

ENTRYPOINT ["bash", "./entrypoint.sh"]